2020-01-07 15:05:51,624 - D:\python_project\zidonghua\TestCase\test01case.py[line:45) - DEBUG:登录成功]
2020-01-07 15:05:51,624 - D:\python_project\zidonghua\TestCase\test01case.py[line:45) - DEBUG:登录成功]
2020-01-07 15:05:51,628 - D:\python_project\zidonghua\TestCase\test01case.py[line:48) - DEBUG:参数错误]
2020-01-07 15:05:51,628 - D:\python_project\zidonghua\TestCase\test01case.py[line:48) - DEBUG:参数错误]
